# Generated by Django 4.0.6 on 2022-10-05 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='OrderHasBeenRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookshelf')),
            ],
        ),
        migrations.AlterModelTable(
            name='orderhasbeenread',
            table='books_bookshelf_has_been_read',
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='has_been_read',
            field=models.ManyToManyField(blank=True, related_name='as_has_been_read', through='books.OrderHasBeenRead', to='books.book'),
        )
    ]


    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name='Orderhasbeenread',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),

        migrations.AlterModelTable(
            name='orderhasbeenread',
            table=None,
        ),
    ]
